---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hanxiaolin.
--- DateTime: 2019/9/30 13:36
---

require("./lib/helper")
require("./app/search")

if arg[1] == nil then
    print('请输入城市名')
    return
end

local city = arg[1]

search.getWeather('上海')


--print(type(arg[1]))
--helper.printTable(arg[0])