---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hanxiaolin.
--- DateTime: 2019/9/30 15:04
---

local http = require("socket.http")
local ltn12 = require("ltn12")
local zlib = require("zlib")
local stream = zlib.inflate()
-- local iconv = require("iconv")


request = {}
request.url = 'http://weather.gtimg.cn/city/'
request.suffix = '.js'

--[[
 请求天气预报api
]]--
function request.get (cityId)
    local api = request.url .. cityId .. request.suffix

    local body = {}
    local res, code, headers =  http.request{
        url = api,
        sink = ltn12.sink.table(body)
    }

    if code ~= 200 then
        print("error: http code not 200" )
        return
    end

    -- gzip
    body = stream(table.concat(body))

    -- match data
    body = string.match(body, "__weather_city = (.*);")
    if body == nil then
        print("error: body not found __weather_city" )
        return
    end

    -- to utf8
    print(body, 33)

    --print(body)
    --if type(response_body) == "table" then
    --    print(table.concat(body))
    --else
    --    print("Not a table:", type(body))
    --end
end

return request

