---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hanxiaolin.
--- DateTime: 2019/9/30 13:35
---

local json = require "cjson"
local util = require "cjson.util"
local cityDetail = util.file_load("./config/city.json", env)
local helper = require("./lib/helper")
local request = require("./app/request")

search = {}

--[[
获取city name
]]--
function getCityId(cityName)
    local t = json.decode(cityDetail)
    for i, v in pairs(t) do
        for si, sv in pairs(v) do
            if sv['name'] == cityName then
                return sv['id']
            end
        end
    end
    return nil
end


function getWeather(cityName)
    -- getCityId
    local cityId = getCityId(cityName)
    print(cityId)

    -- request weather api
    local result = request.get(cityId)
    print(result, 22)

    local weatherB = {
        weatherCityIcon = {
            default = {
                big = "http://mat1.gtimg.com/weather/weatherIco/midImg/",
                mid = "http://mat1.gtimg.com/www/images/qq2012/weather/icon35/",
                small = "http://mat1.gtimg.com/www/images/qq2012/weather/"
            },
            ['00'] = {
                icon = "m0.png",
                weatherTxt = "晴"
            },
            ['01'] = {
                icon = "m1.png",
                weatherTxt = "多云"
            },
            ["02"] = {
                icon = "m2.png",
                weatherTxt = "阴"
            },
            ["03"] = {
                icon = "m3.png",
                weatherTxt = "阵雨"
            },
            ["04"] = {
                icon = "m4.png",
                weatherTxt = "雷阵雨"
            },
            ["05"] = {
                icon = "m4.png",
                weatherTxt = "雷阵雨并伴有冰雹"
            },
            ["06"] = {
                icon = "m6.png",
                weatherTxt = "雨夹雪"
            },
            ["07"] = {
                icon = "m7.png",
                weatherTxt = "小雨"
            },
            ["08"] = {
                icon = "m8.png",
                weatherTxt = "中雨"
            },
            ["09"] = {
                icon = "m9.png",
                weatherTxt = "大雨"
            },
            ["10"] = {
                icon = "m10.png",
                weatherTxt = "暴雨"
            },
            ["11"] = {
                icon = "m17.png",
                weatherTxt = "大暴雪"
            },
            ["12"] = {
                icon = "m17.png",
                weatherTxt = "特大暴雪"
            },
            ["13"] = {
                icon = "m14.png",
                weatherTxt = "阵雪"
            },
            ["14"] = {
                icon = "m14.png",
                weatherTxt = "小雪"
            },
            ["15"] = {
                icon = "m16.png",
                weatherTxt = "中雪"
            },
            ["16"] = {
                icon = "m16.png",
                weatherTxt = "大雪"
            },
            ["17"] = {
                icon = "m17.png",
                weatherTxt = "暴雪"
            },
            ["18"] = {
                icon = "m18.png",
                weatherTxt = "雾"
            },
            ["19"] = {
                icon = "m6.png",
                weatherTxt = "冻雨"
            },
            ["20"] = {
                icon = "m20.png",
                weatherTxt = "沙尘暴"
            },
            ["21"] = {
                icon = "m8.png",
                weatherTxt = "小雨-中雨"
            },
            ["22"] = {
                icon = "m9.png",
                weatherTxt = "中雨-大雨"
            },
            ["23"] = {
                icon = "m10.png",
                weatherTxt = "大雨-暴雨"
            },
            ["24"] = {
                icon = "m10.png",
                weatherTxt = "暴雨-大暴雨"
            },
            ["25"] = {
                icon = "m10.png",
                weatherTxt = "大暴雨-特大暴雨"
            },
            ["26"] = {
                icon = "m16.png",
                weatherTxt = "小雪-中雪"
            },
            ["27"] = {
                icon = "m16.png",
                weatherTxt = "中雪-大雪"
            },
            ["28"] = {
                icon = "m17.png",
                weatherTxt = "大雪-暴雪"
            },
            ["29"] = {
                icon = "m29.png",
                weatherTxt = "浮尘"
            },
            ["30"] = {
                icon = "m29.png",
                weatherTxt = "扬沙"
            },
            ["31"] = {
                icon = "m20.png",
                weatherTxt = "强沙尘暴"
            },
            ["32"] = {
                icon = "m9.png",
                weatherTxt = "飑"
            },
            ["33"] = {
                icon = "m33.png",
                weatherTxt = "龙卷风"
            },
            ["34"] = {
                icon = "m14.png",
                weatherTxt = "弱高吹雪"
            },
            ["35"] = {
                icon = "m18.png",
                weatherTxt = "轻雾"
            },
            ["53"] = {
                icon = "m29.png",
                weatherTxt = "霾"
            }

        }
    }
end

search.getWeather = getWeather

return search