---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hanxiaolin.
--- DateTime: 2019/9/30 13:41
---

function printTable(t)
    for i, v in ipairs(t) do
        print('key => ' .. i .. ', value => ' .. v)
    end
end

helper = {}
helper.printTable = printTable

return helper